apiVersion: v1
kind: Pod
metadata:
  name: a-pod
  labels:
    name: a-pod
spec:
  containers:
  - name: a-pod
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
