apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
  labels:
    name: anti-affinity
spec:
  affinity: 
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              name: a-pod
          topologyKey: kubernetes.io/hostname
    # requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #       - matchExpressions:
    #          key: another-podlabel-key
    #          operator: NotIn
    #          value: another-pod-value
    #       topologyKey: kubernetes.io/hostname 
  containers:
  - name: anti-affinity
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

# avoid putting this pod in the same node, zone, etc. as some other pod(s      
